"""empty message

Revision ID: 80671cb53d7d
Revises: 
Create Date: 2020-03-01 13:36:51.453657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80671cb53d7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sploit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    op.drop_table('sploit')
    # ### end Alembic commands ###
